/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["override"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms/{formKey}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["formSubmissionHistory"];
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["skins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["services"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["languages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deploy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/codegen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["codegen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms/{formKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["formDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{flowKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConfigValueDocument: {
            value?: string;
        };
        ConfigEntryDocument: {
            key?: string;
            value?: string;
            origin?: string;
        };
        FormSubmissionDocument: {
            values?: {
                [key: string]: unknown;
            };
        };
        FormSubmissionResultDocument: {
            submissionId?: string;
            formKey?: string;
            /** Format: int32 */
            declarationVersion?: number;
            resultSummary?: string;
            /** Format: date-time */
            submittedAt?: string;
            effects?: components["schemas"]["EffectOutcomeDocument"][];
        };
        EffectOutcomeDocument: {
            key?: string;
            outcome?: string;
        };
        FormFieldErrorDocument: {
            field?: string;
            code?: string;
            message?: string;
        };
        FormProblemDocument: {
            kind?: string;
            fieldErrors?: components["schemas"]["FormFieldErrorDocument"][];
            permission?: string;
            message?: string;
        };
        SkinDocument: {
            name?: string;
            variables?: {
                [key: string]: string;
            };
        };
        SkinListDocument: {
            skins?: components["schemas"]["SkinDocument"][];
        };
        ServiceDocument: {
            serviceName?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
            status?: string;
        };
        ServiceListDocument: {
            services?: components["schemas"]["ServiceDocument"][];
        };
        OperatorSelfDocument: {
            loginName?: string;
            identityId?: string;
            subjectId?: string;
            permissions?: string[];
        };
        LanguageDocument: {
            code?: string;
            phrases?: {
                [key: string]: string;
            };
        };
        LanguageListDocument: {
            languages?: components["schemas"]["LanguageDocument"][];
        };
        FieldDocument: {
            name?: string;
            kind?: string;
            required?: boolean;
        };
        FormsDocument: {
            formKey?: string;
            titleZh?: string;
            titleEn?: string;
            /** Format: int32 */
            version?: number;
            permission?: string;
            tenantScoped?: boolean;
            fields?: components["schemas"]["FieldDocument"][];
        };
        DeployDocument: {
            applied?: boolean;
            workloads?: components["schemas"]["WorkloadDocument"][];
        };
        WorkloadDocument: {
            name?: string;
            image?: string;
            livenessPath?: string;
            readinessPath?: string;
            memoryLimit?: string;
        };
        ConfigDocument: {
            entries?: components["schemas"]["ConfigEntryDocument"][];
        };
        CodegenDocument: {
            recordName?: string;
            components?: components["schemas"]["ComponentDocument"][];
        };
        ComponentDocument: {
            name?: string;
            javaType?: string;
            typeZh?: string;
        };
        AuditDocument: {
            entries?: components["schemas"]["AuditEntryDocument"][];
        };
        AuditEntryDocument: {
            auditEntryId?: string;
            /** Format: date-time */
            occurredAt?: string;
            tenantId?: string;
            actorIdentityId?: string;
            actorLogin?: string;
            actor?: string;
            actionName?: string;
            actionWordZh?: string;
            actionWordEn?: string;
            actionTarget?: string;
            outcome?: string;
            outcomeWordZh?: string;
            outcomeWordEn?: string;
        };
        FormsIndexDocument: {
            forms?: components["schemas"]["FormIndexDocument"][];
        };
        FormIndexDocument: {
            formKey?: string;
            titleZh?: string;
            titleEn?: string;
            /** Format: int32 */
            version?: number;
            permission?: string;
            tenantScoped?: boolean;
        };
        FormSubmissionListDocument: {
            submissions?: components["schemas"]["FormSubmissionHistoryDocument"][];
        };
        FormSubmissionHistoryDocument: {
            submissionId?: string;
            formKey?: string;
            /** Format: int32 */
            declarationVersion?: number;
            actorIdentityId?: string;
            loginName?: string;
            valuesJson?: string;
            resultSummary?: string;
            /** Format: date-time */
            submittedAt?: string;
        };
        PageIndexDocument: {
            flowKey?: string;
            titleZh?: string;
            titleEn?: string;
            /** Format: int32 */
            version?: number;
            permission?: string;
            tenantScoped?: boolean;
        };
        PagesIndexDocument: {
            pages?: components["schemas"]["PageIndexDocument"][];
        };
        ListSpecDocument: {
            path?: string;
            apiPath?: string;
            itemsKey?: string;
        };
        DetailSpecDocument: {
            path?: string;
            apiPath?: string;
            itemsKey?: string;
            idField?: string;
        };
        SubmitSpecDocument: {
            path?: string;
            apiPath?: string;
            redirectTo?: string;
        };
        PageFlowDocument: {
            flowKey?: string;
            titleZh?: string;
            titleEn?: string;
            formKey?: string;
            /** Format: int32 */
            version?: number;
            permission?: string;
            tenantScoped?: boolean;
            list?: components["schemas"]["ListSpecDocument"];
            detail?: components["schemas"]["DetailSpecDocument"];
            submit?: components["schemas"]["SubmitSpecDocument"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    override: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigValueDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConfigEntryDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    formSubmissionHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormSubmissionListDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formKey: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FormSubmissionDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormSubmissionResultDocument"];
                };
            };
            /** @description Field validation failed — 字段校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormProblemDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the declared permission — 操作员缺少声明权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormProblemDocument"];
                };
            };
        };
    };
    skins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkinListDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    services: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceListDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperatorSelfDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    languages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LanguageListDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormsIndexDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeployDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConfigDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    codegen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CodegenDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    formDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormsDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagesIndexDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pageDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageFlowDocument"];
                };
            };
            /** @description No operator signed in — 没有已登录的操作员 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operator lacks the permission — 操作员缺少这项权限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
