package com.subjex.init;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * InitGenerator — 把 {@link InitConfig} 写成 `.env.example`、`application-local.yml`、`INIT-NOTES.md`。
 * <p>
 * Overwrites existing files in the target directory. Does not start services.
 * 覆盖目标目录已有同名文件。不启动任何服务。
 */
public final class InitGenerator {

    public record Result(Path envExample, Path applicationLocal, Path notes) {}

    public Result write(InitConfig config) throws IOException {
        Path dir = config.targetDir();
        Files.createDirectories(dir);
        Path env = dir.resolve(".env.example");
        Path yml = dir.resolve("application-local.yml");
        Path notes = dir.resolve("INIT-NOTES.md");
        Files.writeString(env, envExampleContent(config), StandardCharsets.UTF_8);
        Files.writeString(yml, applicationLocalContent(config), StandardCharsets.UTF_8);
        Files.writeString(notes, notesContent(config), StandardCharsets.UTF_8);
        return new Result(env, yml, notes);
    }

    static String envExampleContent(InitConfig c) {
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by subjex-init — copy values into your shell or a private .env (do not commit secrets).");
        lines.add("# 由 subjex-init 生成 — 复制到 shell 或私有 .env（勿把密钥提交进库）。");
        lines.add("");
        lines.add("PLATFORM_CONNECTION_VENDOR=" + c.vendor());
        lines.add("PLATFORM_JDBC_URL=" + c.jdbcUrl());
        lines.add("PLATFORM_JDBC_USERNAME=" + c.username());
        lines.add("PLATFORM_JDBC_PASSWORD=" + c.password());
        lines.add("PLATFORM_JDBC_DRIVER=" + c.driver());
        lines.add("SPRING_PROFILES_ACTIVE=local");
        lines.add("");
        lines.add("# Local operator seed (local profile only) / 本地操作员（仅 local profile）");
        lines.add("PLATFORM_OPERATOR_NAME=platform-operator");
        lines.add("PLATFORM_OPERATOR_PASSWORD=change-me");
        lines.add("");
        lines.add("SAMPLE_CONSUMER_HOST=127.0.0.1");
        lines.add("SAMPLE_CONSUMER_PORT=19081");
        lines.add("PLATFORM_APP_HOST=127.0.0.1");
        lines.add("PLATFORM_APP_PORT=8080");
        if (c.includeRedisNotes()) {
            lines.add("");
            lines.add("# Optional: web/ console Redis sessions (multi-replica). Leave unset for in-process sessions.");
            lines.add("# 可选：web/ 控制台 Redis 会话（多副本）。不设则用进程内存会话。");
            lines.add("# Compose Redis (deploy/compose): redis://127.0.0.1:16379");
            lines.add("SESSION_REDIS_URL=");
            lines.add("# Required when SESSION_REDIS_URL is set: ≥ 32 characters; shared across console replicas.");
            lines.add("# 启用 Redis 会话时必填：至少 32 字符；多副本共用同一密钥。见 SECURITY.md。");
            lines.add("OPERATOR_SESSION_SECRET=");
        }
        lines.add("");
        return String.join("\n", lines);
    }

    static String applicationLocalContent(InitConfig c) {
        return """
                # Generated by subjex-init — LOCAL stub. Prefer env vars in production.
                # 由 subjex-init 生成 — 仅本地 stub。生产优先用环境变量。
                # Activate with: SPRING_PROFILES_ACTIVE=local (and/or spring.config.additional-location)
                # 用 SPRING_PROFILES_ACTIVE=local 启用（或 additional-location）。

                spring:
                  datasource:
                    url: %s
                    username: %s
                    password: %s
                    driver-class-name: %s

                platform:
                  connection:
                    vendor: %s
                  local-operator:
                    name: platform-operator
                    password: change-me
                  # One-shot bootstrap stays OFF. See INIT-NOTES.md / docs/operator-permissions.md
                  # 一次性开通保持关闭。见 INIT-NOTES.md
                  operator:
                    bootstrap: false

                server:
                  port: 8080
                """.formatted(c.jdbcUrl(), c.username(), c.password(), c.driver(), c.vendor());
    }

    static String notesContent(InitConfig c) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Local init notes / 本地初始化说明\n\n");
        sb.append("Generated by `subjex-init`. Stubs only — nothing was started.\n\n");
        sb.append("由 `subjex-init` 生成。只是 stub，没有启动任何进程。\n\n");
        sb.append("## Compose hint / Compose 提示\n\n");
        sb.append("From the **repository root** (not this directory):\n\n");
        sb.append("在**仓库根目录**（不是本目录）执行：\n\n");
        sb.append("```shell\n");
        sb.append("docker compose -f deploy/compose/docker-compose.yml up\n");
        sb.append("```\n\n");
        sb.append("Starts PostgreSQL 16, Redis 7, platform-app, sample-consumer, entry-gateway.\n");
        sb.append("See `deploy/compose/README.md`. Does **not** include `web/`.\n\n");
        sb.append("会起 PostgreSQL 16、Redis 7、platform-app、sample-consumer、entry-gateway。");
        sb.append("详见 `deploy/compose/README.md`。**不含** `web/`。\n\n");
        if (c.includeRedisNotes()) {
            sb.append("## Redis / OPERATOR_SESSION_SECRET\n\n");
            sb.append("For multi-replica `web/` console sessions set `SESSION_REDIS_URL` ");
            sb.append("(compose maps Redis to `127.0.0.1:16379`) and `OPERATOR_SESSION_SECRET` ");
            sb.append("(≥ 32 characters). See `SECURITY.md`.\n\n");
            sb.append("多副本控制台会话需设置 `SESSION_REDIS_URL` 与 `OPERATOR_SESSION_SECRET`（≥32 字符），见 `SECURITY.md`。\n\n");
        }
        sb.append("## Optional operator bootstrap (not run by init) / 可选开通（init 不会执行）\n\n");
        sb.append("Init does **not** force bootstrap. Outside `local` profile, provision once then start normally:\n\n");
        sb.append("初始化**不会**强制开通。非 `local` 时手工跑一次再正常启动：\n\n");
        sb.append("```shell\n");
        sb.append("export PLATFORM_OPERATOR_LOGIN=ops-1\n");
        sb.append("export PLATFORM_OPERATOR_PASSWORD='a-long-enough-secret'\n");
        sb.append("# optional: PLATFORM_OPERATOR_ROLE=platform-reader\n");
        sb.append("java -jar platform-app/target/platform-app-0.1.0-SNAPSHOT-exec.jar \\\n");
        sb.append("  --platform.operator.bootstrap=true \\\n");
        sb.append("  --spring.main.web-application-type=none\n");
        sb.append("```\n\n");
        sb.append("Flag defaults to false. Details: `docs/operator-permissions.md`.\n\n");
        sb.append("开关默认关闭。详见 `docs/operator-permissions.md`。\n\n");
        sb.append("## Next / 下一步\n\n");
        sb.append("Source `.env.example` values into your shell, build (`mvn -DskipTests package`), ");
        sb.append("and follow `docs/quickstart.md`.\n");
        return sb.toString();
    }
}
